### ISSUE TITLE
Replace with non-void elements

### ISSUE THREAD

**Issue by kngai** [woudc/woudc-ui#8]
As mentioned in https://github.com/woudc/woudc-ui/pull/6#discussion_r438922571

Lots of HTML elements are in the format of void elements. Best practice is to reserve those for official HTML void elements.

Lines like these:
```html
<nuxt-link :to="localePath('about-faq')" v-text="$t('contact.blurb.faq')" />
```

to be replaced with:
```html
<nuxt-link :to="localePath('about-faq')">{{ $t('contact.blurb.faq')" }}</nuxt-link>
```

**Comment by ahurka** [comment]
Note: when putting links on multiple lines like the example below, the newline after the text somehow gets interpreted as whitespace. Either a space character after the link element is wrapped up in the link (underlined with blue) or a space character is added to the end of the link text, which looks awkward if the link is supposed to come right before a period.

e.g. the style below looks nice but has unwanted side effects.

```
<nuxt-link :to="blah blah blah">
  {{ veryDescriptiveText }}
</nuxt-link>
```

There's supposed to be a `preserveWhitespace` option in Vue that deals with this, but I can't find how to make it work with Nuxt.
